### ISSUE TITLE
Prevent infinite loops from crashing the site

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#10]
....

Relevant issue: https://github.com/sigvef/arktis-tweet-demo/issues/4

**Comment by tbroadley** [comment]
I looked in to this issue a little. It would be challenging to use web workers to detect infinite loops.

Dweets reference a DOM element (`c`) and a graphics context (`x`). Code running in a web worker [can't create these types of objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Functions_and_interfaces_available_in_workers). I also tested passing a DOM element in a message to a web worker: this doesn't seem to be possible either.

So, it seems that `c` and `x` can't be initialized inside a web worker. If `c` and `x` can't be initialized, then the web worker check will only catch infinite loops in code with no references to `c` or `x`.

One option would be to create mocks for the DOM element and graphics context classes, then use those mocks to initialize `c` and `x`.

**Comment by tbroadley** [comment]
I had another idea: It might be possible to replace calls to functions on `c` or `x` before running the code. Maybe with something as simple as a regex, like `x\.[a-zA-Z]+`.

**Comment by sigvef** [comment]
When OfflineCanvas is done we can use that: https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

**Comment by joeytwiddle** [comment]
CodePen detect and break out of infinite loops by instrumenting the code: https://codepen.io/quezo/post/stopping-infinite-loops

This might have a small performance hit, noticeable on really long loops.

They have made their code publicly available: https://blog.codepen.io/2017/03/23/infinite-loop-buster-round-three/

**Comment by lionleaf** [comment]
Instrumenting the code is a pretty good idea! Would even give us finer control both in terms of timing or in loop iterations. I would be happy with such a solution.

**Comment by BalintCsala** [comment]
This might interest you: https://jsfiddle.net/mdnn5c6j/37/

Still needs some work, it handles the functions well, but doesn't keep track of properties (globalAlpha, fillStyle, etc.) and doesn't have the usual dwitter boilerplate (e.g. helper functions)

**Comment by lionleaf** [comment]
Interesting! Can draw some simple stuff :) I worry about being able to get the full dwitter experience piped through the stack though, as this is essentially a white-listing technique. Then again, that might not be too bad. Also interested in seeing some performance numbers.

The more I think about it, I'm leaning towards the CodePen solution mentioned by @joeytwiddle. It leaves the code to run in the same way with a few additional conditional statements. Though I'm curious to see what the performance implications are here as well. Intuitively I would expect this to be faster than a message passing webworker. 

So if someone has some spare time and want to play around with some performance measurement, let me know what you find out.  For both suggestions.

**Comment by lionleaf** [comment]
Interesting that we're exactly back to the same place mentioned by @iver56 on https://github.com/sigvef/arktis-tweet-demo/issues/4 :P

**Comment by circlemachine** [comment]
Mine doesn't technically need the canvas mirror, you only need to run it in a WebWorker once and if it doesn't fail, run the code normally. It doesn't freeze the browser either.

**Comment by circlemachine** [comment]
Oh, sorry, wrong account.

**Comment by BalintCsala** [comment]
Mine technically doesn't need the canvas mirror, unless you want to sandbox it. You can just use it once, and if it isn't infinite, run it normally.

**Comment by BalintCsala** [comment]
@lionleaf I think this can be closed

**Comment by BalintCsala** [comment]
Same with #15
