### ISSUE TITLE
Improve 404 page

### ISSUE THREAD

**Issue by iver56** [lionleaf/dwitter#106]
Currently it says
```
Not Found

The requested URL /d/904 was not found on this server.
```

It would be better if it showed a more user-friendly message, and suggested a link to the front page or something. Could also apply the same style (css) as on other dwitter pages.

Bonus: Maybe show a funny 404-related dweet or something?

**Comment by lionleaf** [comment]
Solved by #112 . Created #116 for your bonus idea 👍
