### ISSUE TITLE
Format dweet posted times in the user's time zone

### ISSUE THREAD

**Issue by tbroadley** [lionleaf/dwitter#125]
If users had a way to set their timezone, dweet post times could be displayed in their time zone.

**Comment by iver56** [comment]
This can also be auto-detected, right? I guess that would be more convenient

**Comment by tbroadley** [comment]
That's true, auto-detection would be better. AFAIK it's quite difficult to do auto-detection on the backend. One solution would be to run some Javascript on page load that would replace all times on the page with the corresponding times in the user's timezone.

**Comment by sigvef** [comment]
https://momentjs.com/ is king of the hill for this kind of stuff ^^

**Comment by tbroadley** [comment]
❤️ moment.js!
