### ISSUE TITLE
Infinite scroll is broken

### ISSUE THREAD

**Issue by iver56** [lionleaf/dwitter#13]
Behavior in Chrome: Infinite scroll doesn't work at all
Behavior in FireFox: Infinite scroll loads one new page, but not pages that should come after that

**Comment by lionleaf** [comment]
What OS are you on?

**Comment by iver56** [comment]
Windows 10

**Comment by lionleaf** [comment]
Is this still a problem?

**Comment by iver56** [comment]
No, it works now, for some reason

**Comment by lionleaf** [comment]
Weird. I'll close this for now, then.  Please reopen if you encounter it again
