### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by 5Mixer** [lionleaf/dwitter#135]
Not sure if this really belongs in a github issue, but I'll post it here any way, it's just an idea. I think it could be awesome if dwitter had some sort of discussion or sharing forum, whether on dwitter.net or maybe as a subreddit. I think there are a lot of neat tricks and things to be shared with golfing canvas code, and the comments of individual dweets aren't the most ideal place, imho. Thanks for dwitter!

**Comment by lionleaf** [comment]
I agree. Having it as part of dwitter would be nice, but an external platform might be easier and quicker. I'm also sure there are some easy to set up django community stuff we could set up. Any particular suggestions?

**Comment by 5Mixer** [comment]
I'm afraid I don't have enough knowledge of Django to recommend specific forum software. As for external sites, I've mentioned reddit could be good because it's really question/showcase -> comments, and has a nice rating system. Managing the forum yourself has the advantage that, perhaps in the future tags could be set up to embed dweets in posts, and I'm sure other nice things too. There's no rush though, so I suppose a good forum solution could be found. Cheers!

**Comment by lionleaf** [comment]
I have claimed https://www.reddit.com/r/dwitter just in case ;) There's also something to be said for a community wiki to cover various techniques.

**Comment by sigvef** [comment]
A community wiki could be useful

**Comment by FireyFly** [comment]
An IRC channel (or some other reasonable real-time chat platform) would be fun! Could always setup a `#dwitter` on freenode if it'd be interesting to others. :)

**Comment by aleksanb** [comment]
It's best if we sanction a single forum for all discussion to avoid fragmentation, as well as for keeping discussions in the open.
Gitter's like irc but usable by normal people, so my vote's goes to that.

**Comment by sigvef** [comment]
Yeah, I think we landedon gitter. There's even a link in the readme!

![image](https://cloud.githubusercontent.com/assets/578029/23436350/79345f48-fe0a-11e6-9e54-f7e695f7b294.png)

**Comment by aleksanb** [comment]
I'm closing this issue then.

**Comment by lionleaf** [comment]
To be fair gitter seems more like a dwitter.net development chat than it
does a dweet creation community. Having a community for the users might be
good. (and we could move dev discussions there too.)
