### ISSUE TITLE
Mention users and dweets in comments

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#150]
Being able to mention other users and dweets in comments in a way that automatically links. I'm planning to use the following syntax:

u/username for a user and d/1337 for dweets.  (or /d/1337 and /u/username?). 

I'm avoiding @ mentions because @ is a valid symbol in usernames (defaults in django). 
And #, while nice for dweet-mentions, could potentially be used for topic-tags at some point in the future. ( #oslo-dweet-compo-17 anyone?)

**Comment by sigvef** [comment]
Remember autocomplete! Also, d/1337 is better than /d/1337.

**Comment by atesgoral** [comment]
#244 with PR #245

**Comment by lionleaf** [comment]
fixed by #245
