### ISSUE TITLE
Flag dweets as particularly heavy on the CPU

### ISSUE THREAD

**Issue by iver56** [lionleaf/dwitter#152]
Some dweets hog the CPU, which makes the user experience bad.

We could let users mark particular dweets as computationally expensive, and let browsing users start these dweets manually (play button or something)

**Comment by iver56** [comment]
For example, when I scroll past this dweet in the feed, it brings the scrolling FPS down to ~0.5
https://www.dwitter.net/d/1611

**Comment by lionleaf** [comment]
Ah nice! I like that idea.

If you're able to click a dweet to pause/play you can let users disable autoplay as well.
Would a single user-report be enough to disable autoplay?

**Comment by iver56** [comment]
Maybe just give moderators this power in the beginning? In that case, a single "report" should be enough

**Comment by lionleaf** [comment]
I believe this is no longer needed with the automatic timeout. Yes; it puts a new constraint on dweets, but so be it.

Report button would still be useful, for other types of dweets.

Closing. Let me know if you disagree
