### ISSUE TITLE
Iframes bleed over dweet cards while loading on iphone

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#156]
Is this common iPhone behavior?

![img_2017-02-28 23 26 49](https://cloud.githubusercontent.com/assets/610925/23439181/77e785a4-fe0d-11e6-82da-16317a9b29b3.jpg)

**Comment by tbroadley** [comment]
I think this might be the solution: http://stackoverflow.com/questions/16937070/iframe-size-with-css-on-ios

**Comment by mxfh** [comment]
only happens on custom aspect ratios after resize c.width.
would actually prefer that the container function checks for the canvas dimension and resizes the container. 
Proposed rationale:
If height is unchanged keep ratio at 16:9, if height is not 1080, resize container as well, so it's possible to have a square canvas.

**Comment by rikardjh** [comment]
@lionleaf Getting this on my iPhone 7 / iOS 11. Think it's just tweets with non standard aspect ratios.

Should be an easy fix with:
.canvas-iframe-container-wrapper{ overflow: hidden; } ?

**Comment by sigvef** [comment]
One thing to think about is that some dweets extend the canvas out of the viewport on purpose to use that area as an off-screen rendering buffer

**Comment by aleksanb** [comment]
I have this frequently on my iPhone.
