### ISSUE TITLE
Don't allow dweeting the default dweet

### ISSUE THREAD

**Issue by puckipedia** [lionleaf/dwitter#162]
One thing I've noticed is that lots of people just press 'dweet' on the home screen, and that will publish the default dweet as one of their own. Maybe it could tell you to think of something unique, and link to an about page or so?

**Comment by iver56** [comment]
It may also be a symptom of the fact that it's not obvious what the "dweet" button does

**Comment by lionleaf** [comment]
This is no longer the case. The dweet button doesn't show up until you change the dweet.
