### ISSUE TITLE
UI: User profile layout and links confusing

### ISSUE THREAD

**Issue by mreinhardt** [lionleaf/dwitter#163]
It's confusing that the username on the top of the profile links back to the homepage, and that the new/top links are for the user.

Recommended change is top keep the main Dwitter new/hot/top header and put a subheader below with the username new/top.

Also, potentially remove the default submit dweet box from the top of the user profile, it'd be nice if the first thing you see there is one of the user's own dweets.

**Comment by sigvef** [comment]
I agree to all of these!

**Comment by stianjensen** [comment]
> It's confusing that the username on the top of the profile links back to the homepage, and that the new/top links are for the user.
>
> Recommended change is top keep the main Dwitter new/hot/top header and put a subheader below with the username new/top.

The header now contains a link back to the frontpage saying 'Dwitter', and the username separately links to the user's profile

> Also, potentially remove the default submit dweet box from the top of the user profile, it'd be nice if the first thing you see there is one of the user's own dweets.

The default submit box has been replaced with a 'Create new dweet' button now. This button also only shows on the front page.
