### ISSUE TITLE
Feature request: turn dwitter URLs in comments into links.

### ISSUE THREAD

**Issue by veu** [lionleaf/dwitter#173]
It would be great if dwitter URLs in comments would be converted to links.

Example input: `Look at https://www.dwitter.net/d/1234`
Example output: `Look at <a href="/d/1234">#1234</a>`

**Comment by tbroadley** [comment]
This is definitely something we should consider doing when implementing https://github.com/lionleaf/dwitter/issues/150.

For now, we do turn URLs in comments into links: https://github.com/lionleaf/dwitter/blob/2d9ea80e632ad4cb06c5cf3166603f668f55f889/dwitter/templates/snippets/dweet_card.html#L92

This isn't perfect, though. A newly-added comment won't have its URLs turned into links until after refreshing the page.

**Comment by atesgoral** [comment]
#244 with PR #245

**Comment by atesgoral** [comment]
@tbroadley Can't repro the "until refresh" issue. This might have been addressed already. See: https://github.com/lionleaf/dwitter/blob/master/dwitter/serializers.py#L23

**Comment by tbroadley** [comment]
@atesgoral You're right! Looks like that issue was tracked in https://github.com/lionleaf/dwitter/issues/184, and was fixed in #204. Thanks for pointing that out.

**Comment by lionleaf** [comment]
fixed

**Comment by atesgoral** [comment]
@lionleaf Actually, can we reopen this? I think @veu wasn't talking about what we've just implemented. It's about also shortening full URLs to the magic pattern, which is something I was hoping to land in a later PR. This is a nice feature to have.

**Comment by lionleaf** [comment]
Woops, I was a bit too quick. Reopened

**Comment by tbroadley** [comment]
Should this issue be closed (because of cc5be1b)?

**Comment by veu** [comment]
Sure 👍
