### ISSUE TITLE
Feature request: share dweet as gif

### ISSUE THREAD

**Issue by snnw** [lionleaf/dwitter#177]
The rendering should probably be done client-side. Something like https://github.com/jnordberg/gif.js/ should do the trick. Uploading to twitpic through their API and integration with Twitter would be great.

**Comment by iver56** [comment]
That would be awesome 💯 Feel free to create a pull request 👍

**Comment by aleksanb** [comment]
If you use MediaRecorder you can record directly to a webm from a canvas, the same way that the site https://www.musicvideodispenser.com/ does it.
Then the webm can be shared (and twitpic can reencode it to a gif if they want!)

Currently there are some implementation issues to make such a thing for dwitter as the canvas is within an iframe, so the recording would have to be inside the content loaded in the iframe, which breaks separation somewhat.

**Comment by mxfh** [comment]
would welcome this, doesn't even need another website or api, but export button would be easy, just pull each frames toDataURL and let some workers pack them into a gif, as already mentioned see: https://jnordberg.github.io/gif.js/

**Comment by lionleaf** [comment]
Yeah, this is a great idea we're coming back to from time to time. If it can be done client side that would be awesome, as I'm a tad bit resistant to add too much server side computation. Very happy to have survived hackernews front page on the smallest digitalocean droplet without issues.

Doing it client side also means you're sharing what you're seeing, in the cases where it might be different on the server (emoji versions for instance)

**Comment by iver56** [comment]
Maybe the client side rendered gif could also be stored on the server, so it can later be referred to in open graph ("og") meta tags, so the dweet looks nice when its link is shared on social media

**Comment by atesgoral** [comment]
Could be useful for this: https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by lionleaf** [comment]
Implemented in #325
