### ISSUE TITLE
Direct-link to dweets

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#18]

**Comment by PhiLhoSoft** [comment]
Yes, indeed, useful to tweet a good dweet... :smile: 
The fullscreen link is a kind of bookmark, but then we can't easily see the code (unless doing "View source" and searching...).

**Comment by iver56** [comment]
I wanted to share a dweet on Hacker News today :smile: I need this feature ;P
https://news.ycombinator.com/item?id=12312196

**Comment by iver56** [comment]
The page for a single dweet could look like this, for example:

![image](https://cloud.githubusercontent.com/assets/1470603/17792108/5690c6ec-659f-11e6-811b-e272bc9d67fb.png)

**Comment by iver56** [comment]
Getting the url for a dweet could be like this:

![image](https://cloud.githubusercontent.com/assets/1470603/17792483/3507c2ee-65a1-11e6-89e0-957f1367f057.png)
