### ISSUE TITLE
Autoplay doesn't work properly after long comment threads have loaded

### ISSUE THREAD

**Issue by peterhgombos** [lionleaf/dwitter#194]
After loading all comments on a long comment thread, scrolling down starts playing the dweets earlier, and stops playing them while they're in the middle of the screen.

To reproduce in prod:
1. Go to top
2. Find a dweet with many comments (for instance https://www.dwitter.net/d/1494)
3. Expand the comment thread.
4. Scroll further down.

**Comment by lionleaf** [comment]
Thanks, nice find!

**Comment by tbroadley** [comment]
The same thing happens after clicking on the "Create new dweet" button.
