### ISSUE TITLE
Pause/resume

### ISSUE THREAD

**Issue by atesgoral** [lionleaf/dwitter#205]
Could be nice for examining a still, or to take a controlled screenshot. Could be super useful when authoring a dweet since live preview of the code that is being typed can lead to infinite loops, super heavy processing that hog up the CPU, etc.

**Comment by lionleaf** [comment]
Slightly less important now that we have loop timeouts; but it could still be useful. But useful enough to clutter the amount of links under the dweets already?

I was originally thinking that click on a dweet would pause/play it; but that would probably interfere with dweets that are interactive

**Comment by lionleaf** [comment]
Related to #158

**Comment by atesgoral** [comment]
This could as well be a separate tool! I was thinking of creating a dweet debugger that can also have a real-time display of variable values (and even make them tweakable) by using dat.gui or something else.
