### ISSUE TITLE
Hot, New, Top and Random

### ISSUE THREAD

**Issue by joeytwiddle** [lionleaf/dwitter#210]
I would really love a "Random" or "Shuffle" page so I can browse through older dweets which I cannot easily reach from the three existing feeds.

Call it "Old" if you want to stick with the three-letter theme. ;)

**Comment by lionleaf** [comment]
I like the idea! Discoverability of old dweets is something that need some work. Searching and hash tags might help too, but this was a simple and effective suggestion. 

PS: a hidden trick to view old dweets:  https://www.dwitter.net/new/page/42   just change 42. Works for hot and top too. It's remaining from before infinite scroll, and might stop working in the future.

**Comment by joeytwiddle** [comment]
That trick is good to know, thanks!

**Comment by lionleaf** [comment]
Implemented in #212, thanks :)

Deployed and looking good
