### ISSUE TITLE
Reset Password not working

### ISSUE THREAD

**Issue by Froff** [lionleaf/dwitter#22]
Attempting to reset you password results in a Server Error (500)

**Comment by lionleaf** [comment]
Thanks! I'll have a look at it when I get time. If you want I can manually
reset your password meanwhile?

**Comment by Froff** [comment]
Yeah thanks that would be nice
On Mar 11, 2016 11:06 PM, Andreas Løve Selvik <notifications@github.com> wrote:Thanks! I'll have a look at it when I get time. If you want I can manually
reset your password meanwhile?

**Comment by stianjensen** [comment]
This might be caused by a lack of an email backend?

I suggest using mailgun, which provides 10,000 sent emails every month for free.

The [django-mailgun](https://pypi.python.org/pypi/django-mailgun) package is very easy to set up.
