### ISSUE TITLE
those pesky adblock extensions <might> block the share button

### ISSUE THREAD

**Issue by andrienko** [lionleaf/dwitter#236]
I am using the [ublock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) extension, with [these filters](https://i.imgur.com/wFavT6O.png) active.

And it [blocks the share button](https://i.imgur.com/BgkCFOg.png) (protecting my privacy, I guess) with its "cosmetic filters". I believe that basically anything having a "share-button" className gets stripped out.

Not really an issue-issuem, but probably rename the "share" to something like "permalink" (as it doesn't really share anything)?

**Comment by joeytwiddle** [comment]
I'm not a huge fan of the *share* button. I think it should be a normal link to the dweet page, with the dweet's number, like so:

[#1234](https://www.dwitter.net/d/1234)

I can't explain why, but I feel that's just more idiomatic of the web.

(It could also have a share button next to it that promotes ~popular~ social network monopolies!)

**Comment by lionleaf** [comment]
I think renaming to `link` or changing it to [d/123](https://www.dwitter.net/d/123) would both be acceptable.

**Comment by lionleaf** [comment]
Does this still happen after the changes to the share box?

**Comment by stianjensen** [comment]
I didn't remember to change the class name of the share link itself, so if that's what got caught in the filter, it's probably still blocked.

**Comment by lionleaf** [comment]
Haha, I guess you could. But the intent was probably not hiding permalinks :P 

Does it block it when running locally as well? If so, you could try changing the tag names, or the text name itself. If it's just a tag that would be great :)

**Comment by joeytwiddle** [comment]
Captain, as far as I can tell, the `share-button` class is not serving any purpose except to excite UBlockO.

If I **remove** the `share-button` class, or if I **rename** it to `dwitter-share-button` then the link re-appears!

Get blocked: `share-button`, `share-link`, `SHARE-button`, `button-share`

Do not get blocked: `share`, `cher`, `chair`, `cher-button`, `sharia-button`, `dwitter-share-button`, `sharing-button`, `share-button-noblock`

Any preferences? As I say, it's not currently used for anything, so removing it is also an option. (Stian's new popover is attached by the `data-popover` not the classname.)

**Comment by stianjensen** [comment]
> `cher-button`, `sharia-button`, `dont-call-me-sharely`

I would be pro any of these 😄 , but just removing it should do the trick. It serves no purpose anymore.
