### ISSUE TITLE
Add "New Dweet" Button to all pages.

### ISSUE THREAD

**Issue by MrMcCrary** [lionleaf/dwitter#237]

**Comment by joeytwiddle** [comment]
Now that it's in the header, has this requirement been fulfilled?

**Comment by lionleaf** [comment]
It seems to be missing from the /u/ pages for instance: https://www.dwitter.net/u/joeytwiddle 

<img width="847" alt="screen shot 2018-01-02 at 8 30 57 pm" src="https://user-images.githubusercontent.com/610925/34509177-df814566-effb-11e7-83a9-741a6c8410d5.png">
