### ISSUE TITLE
"remix of #n by username" text misleading about the way to link to dweets

### ISSUE THREAD

**Issue by atesgoral** [lionleaf/dwitter#250]
Probably due to the "#n" text in remixed dweets, people have picked up the convention of referring to other dweets with the #n syntax. Some ideas:

* Change the remix text to say "remix of d/n by username" or even "remix of d/n by u/username" (and maybe make the d/ and u/ parts slightly faded out) as a hint to users on how to refer to other dweets/users -- but that might look ugly
* Also accept the #n format as a way to link to dweets -- this should be a problem for future #tags since tags will very likely not be numeric.

**Comment by sigvef** [comment]
I was thinking exactly the same! :D

**Comment by lionleaf** [comment]
I agree! I think d/ and u/ slightly faded is the way to go! 👍
