### ISSUE TITLE
navigation links on user page does not get bold

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#264]
User page:
<img width="578" alt="screen shot 2018-01-17 at 10 44 51 pm" src="https://user-images.githubusercontent.com/610925/35084285-1c3197b2-fbd8-11e7-945c-1000c58c506e.png">

vs default page:

<img width="427" alt="screen shot 2018-01-17 at 10 45 39 pm" src="https://user-images.githubusercontent.com/610925/35084296-294989fa-fbd8-11e7-90b7-dd428b762c3d.png">

**Comment by atesgoral** [comment]
Might want to add some colour instead of changing the weight since weight changes make the letters shift in position.
