### ISSUE TITLE
Characters after u/username prevent magic link insertion

### ISSUE THREAD

**Issue by atesgoral** [lionleaf/dwitter#273]
Probably should make the regex a bit more forgiving.

Live example: Punky's comment on https://www.dwitter.net/d/6281

>Based on u/sadropol's Christmas tree.

**Comment by lionleaf** [comment]
This seems to work:

<img width="256" alt="screen shot 2018-01-21 at 5 50 45 pm" src="https://user-images.githubusercontent.com/610925/35201857-9f83d05a-fed3-11e7-81c3-c5cc2f2257e2.png">

When does it not work?

**Comment by lionleaf** [comment]
(like this maybe u/lionleaf) ?

**Comment by atesgoral** [comment]
Yeah, they have to adjacent non-word characters like apostrophes.
