### ISSUE TITLE
Login and registration doesn't show errors

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#279]
Errors like "wrong username/password", "that user already exists" etc etc are not being shown on registration and login page.

Should also add a note on the login page that usernames are used, not emails. And that it's case sensitive

**Comment by diceroll123** [comment]
I'm kinda conflicted here, you can have two users, `steve` and `STEVE`... 

Well, the development build lets me do that, I'm unsure if prod is doing it. 🤔 Is this intentional?

**Comment by lionleaf** [comment]
It's default behaviour from djang-registration-redux; so it's the current behaviour. Enforcing a new policy on that going forward is probably a good idea :)

However, that's a separate topic. This issue is just the lack of visual feedback when things are wrong. Right now it just doesn't respond.

**Comment by stianjensen** [comment]
Case sensitive user names is the default in Django, even.

**Comment by dwitterer** [comment]
Fixed in #325. You should close this issue or merge it with that pull request or something...
