### ISSUE TITLE
New dark theme misaligns menu on small screens / phones

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#295]
<img width="299" alt="screen shot 2018-03-01 at 9 57 41 pm" src="https://user-images.githubusercontent.com/610925/36885852-56931f4c-1d9e-11e8-9fde-f861ea042214.png">
<img width="244" alt="screen shot 2018-03-01 at 10 18 02 pm" src="https://user-images.githubusercontent.com/610925/36885880-7aeb8528-1d9e-11e8-9570-2c27d834fc3e.png">

**Comment by moonrisewarrior** [comment]
Fixed - PR 296.

**Comment by lionleaf** [comment]
Fixed by #296
