### ISSUE TITLE
Throwing errors in dweets stops the FPS counter

### ISSUE THREAD

**Issue by AnnanFay** [lionleaf/dwitter#298]
Using `throw` to pass messages to the viewer is useful. For examples see: https://www.dwitter.net/d/7263 and https://www.dwitter.net/d/7075

Currently if you throw errors in every function call it will not time the code so the FPS counter stops working. Maybe we can change the code to something like:

      try {
        stats.begin();
        u(time);
        stats.end();
        displayError("");
      } catch (e) {
        stats.end();
        displayError(e);
        throw e;
      }

**Comment by lionleaf** [comment]
That seems reasonable to me 👍
