### ISSUE TITLE
Deleting a dweet deletes all replies!!! 

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#30]
Cascading deletes? :(

**Comment by stianjensen** [comment]
Cascading deletes are default for django model foreign keys.

You can override it to SET_NULL instead:
https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.SET_NULL

I suggest to provide an explicit value for `on_delete` on all foreign keys (that will also be required as of Django 2.0)
