### ISSUE TITLE
Visual bug on share card

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#310]
With the new share box from #309 , the u/ and d/ seems to shine through the box.

Windows 10, Chrome

![image](https://user-images.githubusercontent.com/610925/38400695-34cb4cbc-3906-11e8-8119-30f87f80d0a7.png)

![image](https://user-images.githubusercontent.com/610925/38400681-2706c80e-3906-11e8-94d7-1b2de09aa478.png)

@stianjensen  ^

**Comment by stianjensen** [comment]
Must have forgotten a background color. Only tested on non-remixed dweets locally.
