### ISSUE TITLE
All the 'share' links have an empty href

### ISSUE THREAD

**Issue by joeytwiddle** [lionleaf/dwitter#317]
In `dweet_card.html` we used to have:

    <a class="dweet-option share-button" href="{% url 'dweet_show' dweet_id=dweet.id %}" target="_blank">share</a>

but now we have:

    <a class="dweet-option share-button" href="" data-popover=".share-container">share</a>

That means we cannot right-click on the share link to open that dweet in a new tab, which is something I find useful. Is there another way I should be doing that?

I will try to restore it.

(Full disclosure: I originally put that href there back in c6dc918210a474e73b5f86f2a8ad4e4d907bb88f)
(It was removed in @stianjensen's recent 7f8a782b94ac8397fff48d725fad54e85f0bcd29, possibly for reasons)

**Comment by stianjensen** [comment]
Sounds good. Didn't think about this us e-card, sorry!
