### ISSUE TITLE
Fix the width of the bars on the favicon

### ISSUE THREAD

**Issue by dwitterer** [lionleaf/dwitter#339]
During recent changes, me and lionleaf have somehow made it so that the bars on the favicon are very wide. There are different options for solving this, and so I'm opening this issue for people to discuss and suggest different configurations for the bars. Generally, lionleaf wants:

- The height of the bars to be 4x their width
- The gaps between the bars to be same as their width
- And ideally, the margins on either side of the bars to be the same size

**Comment by dwitterer** [comment]
Currently, I've got:
- 3px margins either side
- 6 px by 24 px bars
- 4 px by 24 px gaps between bars

But this makes the bars look really thick for some reason.

**Comment by dwitterer** [comment]
I think I'll go with an extra 1px on the right... But feel free to put suggestions in here I guess.

**Comment by dwitterer** [comment]
Okay, so lionleaf is busy this week, but here is what I've got with messing around in GIMP, that I think looks quite cool:

![dwitter_logo](https://user-images.githubusercontent.com/36137355/39447723-a03518bc-4cba-11e8-9d81-fe9005f3651e.png)

This is one I made first, but lionleaf said he wanted to stick to the bars design and avoid being too enterprise-like.

![dwitter_bars_logo](https://user-images.githubusercontent.com/36137355/39447709-928f138e-4cba-11e8-8e4e-d3a915b0740f.png)
 
So then I made this which lionleaf seems to like most... The drop shadows can be adjusted if needed, and it has a nice, rounded appearance, with a rounded white background. Click on it to see the full image.

What do you guys think?

**Comment by joeytwiddle** [comment]
My two cents:

- I'm not a fan of the shadow. It feels like unnecessary detail to me. Simpler might be superior.
- Many popular sites (but not all) use a single colour transparent logo, without any background. This has some advantages for marketing (easy to invert the icon, or place it onto a different background).
![joey s google-chrome at 7 42 38 pm on tuesday 1 may 2018](https://user-images.githubusercontent.com/911799/39476500-be9a824a-4d8e-11e8-8175-eebd3de17fc3.png)
- But when I saw the rounded border of your white background, I actually quite liked it!

I recommend the [Real Favicon Generator](https://realfavicongenerator.net/) for creating a full set of images for all devices. It might be good to feed a large (1024x1024) image into that.

I knocked up a really simple re-arrangement: 6x24 blocks with a 6px gap. That leaves a margin of only 1px but I think that's ok; favicons don't really need a margin.

![default-favicon-32x32-6x4-transparent](https://user-images.githubusercontent.com/911799/39475807-61862336-4d8c-11e8-8991-80b72f64bea3.png) (transparent)
![default-favicon-32x32-6x4-white-background](https://user-images.githubusercontent.com/911799/39475810-62d18776-4d8c-11e8-8e7f-b1e70219ec0d.png) (on white)

I also tried to hide a D in the blocks, but I'm not so excited by the results:
![favion-default-blocks-making-a-d-1](https://user-images.githubusercontent.com/911799/39476176-a2869004-4d8d-11e8-8b83-a357475123de.png)
![favion-default-blocks-making-a-d-2](https://user-images.githubusercontent.com/911799/39476180-a4e1f12c-4d8d-11e8-826c-aaf49d69ea5a.png)

**Comment by joeytwiddle** [comment]
For posterity I would like to record some of the other designs people came up with on Discord.

<a target="_blank" href="https://user-images.githubusercontent.com/911799/39483232-4f755be0-4da4-11e8-9a66-7e80ccc70a04.png" title="(0 related links)"><img width="128" src="https://user-images.githubusercontent.com/911799/39483232-4f755be0-4da4-11e8-9a66-7e80ccc70a04.png" alt="dwitter" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483233-4fbeda68-4da4-11e8-863b-b57dae0fa417.png" title="(0 related links)"><img width="128" src="https://user-images.githubusercontent.com/911799/39483233-4fbeda68-4da4-11e8-863b-b57dae0fa417.png" alt="dwitter_logo_1" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483234-4fef69d0-4da4-11e8-9285-7d7fbe4852fb.png"><img width="128" src="https://user-images.githubusercontent.com/911799/39483234-4fef69d0-4da4-11e8-9285-7d7fbe4852fb.png" alt="dwitter2" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483236-5028192e-4da4-11e8-8249-e1c3fed65362.png"><img width="128" src="https://user-images.githubusercontent.com/911799/39483236-5028192e-4da4-11e8-8249-e1c3fed65362.png" alt="dwitter_logo_2" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483237-5066c214-4da4-11e8-888f-b7b2675cffdc.png"><img width="128" src="https://user-images.githubusercontent.com/911799/39483237-5066c214-4da4-11e8-888f-b7b2675cffdc.png" alt="dwitter3" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483273-69590322-4da4-11e8-8d07-bca2092fcb9a.png"><img width="128" src="https://user-images.githubusercontent.com/911799/39483273-69590322-4da4-11e8-8d07-bca2092fcb9a.png" alt="tweetdweet" style="max-width:100%;"></a><a target="_blank" href="https://user-images.githubusercontent.com/911799/39483274-69a6ac58-4da4-11e8-98b9-841272259722.png"><img width="128" src="https://user-images.githubusercontent.com/911799/39483274-69a6ac58-4da4-11e8-98b9-841272259722.png" alt="dwitter-default-blue-d-2" style="max-width:100%;"></a>

**Comment by dwitterer** [comment]
Wow, this is still open? Closing as inactive and not needed anymore....
