### ISSUE TITLE
Edit a published dweet, via comments?

### ISSUE THREAD

**Issue by joeytwiddle** [lionleaf/dwitter#356]
Motivation:

- Sometimes, a day or two after publishing a dweet, the author finds a bugfix that will make the dweet work on more browsers, or just work more efficiently. They would like to update the dweet, without republishing all over again.

- Similarly, someone publishes a dweet and then someone else finds a way to golf it down. The original author might want to display the golfed version instead of the original.

lionleaf had a proposal for this sort of thing, which I cannot find right now, but I will try to paraphrase, and add in my own part:

Plan A:
- People should be able to post remixes of a dweet, not as a new dweet, but as a comment on the original dweet.
- The original author should be able to select any comment-remix they want to display. This would replace the original ("by Foo, remixed by Bar").
  (If they do that, perhaps the original mix should be injected into the early comments, so it isn't lost.)

Alternative, plan B:
- There is no way for the author to replace the original dweet. But users can click on the comment remixes, and the code will appear in the editor box. Lazy!

This proposal seems a bit weird and complicated. And this might diverge too much from lionleaf's original idea. There are definitely pros and cons... Any better way?

**Comment by lionleaf** [comment]
#71.

**Comment by joeytwiddle** [comment]
I think I had read iverjo's suggestion before, and was just regurgitating it!
