### ISSUE TITLE
/random - all awesomeness is resetting to 1

### ISSUE THREAD

**Issue by kipkat** [lionleaf/dwitter#361]
### In /random, the score indicator _(class="score-text")_ becomes 1 when visiting the /random page (until you like the dweet.)
**More information:**
- Even if you liked it before visiting /random, it still resets
- If you un-like it after that, it does not reset
Probably it is a database error or something, but I created an easy fix (temporary):
```js
b = document.getElementsByClassName("like-button")
for(let x=0; x<b.length; x++){b[x].click();b[x].click()}
```
Paste that in the Developer Web Console to make fix the visible/loaded ones.

**Comment by lionleaf** [comment]
Thanks for the bug report!

I am aware of this issue. I think it stems from a bug where the annotate on [0] is not functioning correctly when the queryset sorts by '?' (random). 

I've been looking at a fix, but I wanted to avoid iterating over all the returned dweets in python. I'm also hoping this would solve itself when I get around to upgrading to a newer version of Django.

[0] https://github.com/lionleaf/dwitter/blob/master/dwitter/feed/views.py#L78

**Comment by kipkat** [comment]
Yeah, probably **2.0.*** > 2.0.2 will fix that.

**Comment by kipkat** [comment]
EDIT: Now even if you liked one of them, still resets.
