### ISSUE TITLE
Only Unicode and GSM Characters Allowed System needed.

### ISSUE THREAD

**Issue by kipkat** [lionleaf/dwitter#362]
Some people are obfuscating the code, using non GSM Characters (no Unicode), making the code shorter. Example: [/d/7905](https://www.dwitter.net/d/7905)
- The Chinese Characters are not present in GSM charset
- The original length of 184 characters is now 140. I find compressing cheating because of evading the 140 length rule.
- More examples of compressing: [/h/compressed](https://www.dwitter.net/h/compressed)
---
Does a system like
```python
if isinstance(dweet, str): # ... ordinary string
elif isinstance(dweet, unicode): # ... unicode string
else: # not string
```
will be useful for filtering the code?

**Comment by lionleaf** [comment]
I don't mind the fact that some people push dwitter to the limit and play around with interesting compression schemes, as long as it doesn't become the norm or "required" to make anything interesting.

You're just saying that I should count complex unicode characters as 2 characters? Not that you want to make certain characters illegal? (emojis are essential to dweets, so no plans to do that!)

I just did a check on various character-counting social platforms, and they do indeed count more characters for those compressed dweets than a regular dweet. In the name of having a dweet actually fit in 140 characters on other platforms I'd be open to yet another discussion on character counting.

BUT: I would not invalidate old dweets. And I'm leaning towards leaving it as is.

What does the community think?

PS: If you're just talking about character length, can I change the title of this issue to reflect that?

**Comment by kipkat** [comment]
I don't know. Emojis already count as 2 characters. I was just thinking that use the compression techniques used by those people is cheating. If you think it is ok, then is no problem. I will leave the Issue open for 2-3 days to see if anybody has another opinion about this.
