### ISSUE TITLE
Dweets can still redirect the iframe

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#367]
Now that the CSP-header has been added, loading external content into a dweet shouldn't be possible. However, dweets can still redirect the whole iframe, for instance through 

`document.location="//www.example.com/";`

Example dweet:
https://www.dwitter.net/d/7645

Any ideas on how to block this? As far as I can tell there aren't any way to whitelist domains for an iframe? Could we actively intercept attempts to change document.location?

**Comment by stianjensen** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src

**Comment by lionleaf** [comment]
Ah yes, I was thinking in terms of the CSP within the iframe (dweet.dwitter.net). I have now added a more restrictive policy to the main page (www.dwitter.net), which blocks this!

Solved.

I no longer know of any ways to load an external resource.
