### ISSUE TITLE
Green theme discussion thread

### ISSUE THREAD

**Issue by dwitterer** [lionleaf/dwitter#384]
Okay, so we curently seem to have two competing version of a "green hacker theme" for Dwitter round here... One is mine (#379) and the other is the current green theme made by kipkat. I'd like to hear everyone's opinions on this, to help us decide which one is better and which one to implement. To avoid flooding the PRs, I opened a new issue.

![screenshot from 2018-08-22 00 41 55](https://user-images.githubusercontent.com/36137355/44459461-a51b2d80-a601-11e8-8c14-7572cc7bdd92.png)

Mine

VS

![screenshot from 2018-08-22 11 51 46](https://user-images.githubusercontent.com/36137355/44459488-c5e38300-a601-11e8-9bca-03a4cef91b2d.png)

![screenshot from 2018-08-22 11 52 23](https://user-images.githubusercontent.com/36137355/44459523-e14e8e00-a601-11e8-8470-f3272f6c9c0a.png)

Kipkat's theme

**Comment by lionleaf** [comment]
As mentioned in #379, while the green theme is now part of dwitter, and not directly under kipkat's ownership, I'd prefer to not go against his wishes for what he wanted in this case.

On a related note, I think the proper solution to these themes might be a "custom theme" functionality in dwitter where you can upload/paste some css to change the theme. And then you and kipkat could maintain your own themes and there could be a repository of themes somewhere. I'd much prefer that to having a number of themes directly on dwitter
