### ISSUE TITLE
Fix "Show more comments" being unnecessarily displayed

### ISSUE THREAD

**Issue by dwitterer** [lionleaf/dwitter#396]
I discussed this with LL a while back, but I forgot about it since. There is a minor issue with the comments section in that the "show more comments..." text is displayed when there is above a certain number of comments, but that number does not include the stickied comment. This is an error somewhere in the django code for the comments, and shouldn't take too long to fix, but is very annoying.

**Comment by kipkat** [comment]
Yeah, the "show older comments" isn't really hiding older comments, just not hiding the last 4-5 comments.

**Comment by lionleaf** [comment]
This be fixed by #403 Closing
