### ISSUE TITLE
Use pagination to handle pages

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#4]
https://docs.djangoproject.com/en/1.9/topics/pagination/

**Comment by PhiLhoSoft** [comment]
Can be useful, particularly if we can choose the number of dweets per page: too much dweets running can slow down the browser a lot (particularly Firefox).

Related side suggestion: in infinite scroll mode, stop (remove?) dweets scrolled out (perhaps not the immediate one, for fluidity / cache).

**Comment by lionleaf** [comment]
Dweets not shown are paused at the moment, but for a long scroll freeing memory might be something to look into too, especially if there are memory-intensive dweets.
For now the automatic start and stop seems to work well, especially with #52 in place

**Comment by wesleywerner** [comment]
I would like to see pagination, it would obsolete #66 and keep the max memory used in check.

**Comment by joeytwiddle** [comment]
Another advantage with pagination is that it would allow search engines to index the site.

That might make it possible for us to search for dweets that use a particular API function, or have keywords in the comments. e.g. "voronoi"

**Comment by tbroadley** [comment]
Huh, I thought Google would have indexed the individual dweet pages (e.g. https://www.dwitter.net/d/1900), but apparently not: https://www.google.ca/#q=voronoi+site:dwitter.net

**Comment by joeytwiddle** [comment]
@tbroadley Oh yes we do want it to index the individual dweet pages. But it needs to *find* those pages somehow.

Currently it can find them by following the "share" links on the feed pages. But it might only be able to see the first 10 of each feed.

**Comment by lionleaf** [comment]
Fixed by #351 . Issue was about using the django paginator to handle pages, which is now the case.

There are other issues around SEO, but that can be handled separately. (If infinite loop js doesn't load there is a next-page at the bottom of each page. And you can also do ?page=5 now

**Comment by lionleaf** [comment]
Though I realize this issue has also been taken as a "let's move from infinite scrolling to pagination". 

I suggest we open a new issue if people still want that. I can see it be handy in certain cases, but I want to keep infinite scrolling as the main mechanism. Solving resource is important though.

PS: You can already do this: https://www.dwitter.net/top?page=100
