### ISSUE TITLE
Bug: Playback speed tied to monitor refresh rate

### ISSUE THREAD

**Issue by pavelb** [lionleaf/dwitter#414]
I have a 165hz monitor and dweets run at nearly three times the normal speed on it. I have to check them on my phone to see what they are supposed to look like.

**Comment by pavelb** [comment]
I think the problem is [here](https://github.com/lionleaf/dwitter/blob/master/dwitter/templates/dweet/dweet.html#L233)  with requestAnimationFrame. The surrounding code assumes that this call rate-limits itself to 60hz but in reality it rate-limits to the monitors native refresh rate (see the note in [Section 5](https://www.w3.org/TR/animation-timing/#processingmodel)). setTimeout should be used to manually rate-limit calls to requestAnimationFrame to the desired fps.

**Comment by pavelb** [comment]
Actually it looks like using setTimeout is not advised. If animation is to be done it should be done at the timing of requestAnimationFrame. So we should continue to run at the rate of requestAnimationFrame but we should do nothing on certain frames if we sense we are animating too quickly.

**Comment by lionleaf** [comment]
Hi @pavelb, thanks for the report!

From the referenced commit I can see you've already started on a fix. Awesome! 

And you're right, requestAnimationFrame is the recommended way to deal with frame timing.

Skipping frames sounds like a potentially good solution. The timing might cause some slight flicker as 165hz isn't a multiple of 60 (and neither is the popular 144Hz). But dwitter is written with the assumption of 60fps for consistency and determinism, so skipping frames is probably your best bet.

Let me know how it looks (I don't have a high refresh rate monitor available)

**Comment by prplz** [comment]
Hey @pavelb, you should change the setting of nextFrameMs to `nextFrameMs = Math.max(nextFrameMs + 1000 / FPS, now);`.
This allows nextFameMs to properly accumulate time for refresh rates which are not multiples of 60. The `max` part accounts  for "lost time", for example when the tab isn't active.

**Comment by lionleaf** [comment]
For refresh rates that are not multiples of 60, there are two different approaches we could take:

1) make sure the math keeps track of accumulated error and corrects itself to an average of 60fps over time. This will keep the speed of the dweets "correct" but it might cause a slight jitter for every "correction frame". Someone with a high refresh monitor should check how bad it is.

2) we refresh consistently at the closest divisor of the refresh rate to 60. For 144Hz this might mean 72 Hz (skipping every other frame). This will make the dweets run very smoothly (unless they drop frames). But it will make the dweets appear to move slightly faster/slower.

Option 1 is probably the most straight forward and garantueed to work reasonably well, but if the stutter is visible option 2 might be better.

Thoughts from the high refresh rate monitor people?

**Comment by pavelb** [comment]
My above pull request ensures that u(t) is never called twice in a time span of 1/(60 hz). It does this by dropping triggers of requestAnimationFrame that would violate the above rule. The net effect is option (2) above. The benefit is that the frames are all evenly spaced. I looked at newegg.com for popular monitor refresh rates and computed the corresponding throttled rates

60hz -> 60hz
75hz -> 37.5hz
120hz -> 60hz
144hz -> 48hz
165hz -> 55hz

Most of these looks okay but 75hz would be played back a third slower than 60hz.

We don't need to cap strictly under 60hz. If we cap to 75hz we get

60hz -> 60hz
75hz -> 75hz
120hz -> 60hz
144hz -> 72hz
165hz -> 55hz

Now 75hz and 144hz are outliers that are rendered a quarter faster than 60hz while the others are very close to 60hz.

I've set my 165hz monitor to run at these refresh rates to test things out. None of them look particularly bad. A third slower or a quarter faster look jarring on paper but the few dweets ive tried don't look obviously off. And they look much better than the current almost 2.75x rate im getting on my 165hz.

Let me take a look at some variable frame pacing implementations.

**Comment by pavelb** [comment]
I've tested (a) @prplz approach and (b) a generalized form of my "at most n frames in last n/FPS time" approach. I couldn't visually tell a difference between them and the fixed, lower frame-rate approach. The pattern of dropped frames was a bit random for (a) and predictable for (b) but they looked similar running at full speed. There is always normal rendering time jitter plus there is jitter in how time and frame variables are converted into coordinates on the canvas. I am going with the variable frame rate approach as it has that 'u is called 60 times per second' property that is advertised and it looks fine to me.
