### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [lionleaf/dwitter#417]
Hi, I guess this project has no logo. I like to contribute to open source software. If you want, i can design a logo for you. What do you say?

**Comment by kipkat** [comment]
It would be cool something like a SVG bird made of letters of something. I still don't think @lionleaf would like a logo.

**Comment by dwitterer** [comment]
Yeah, I've discussed it with lionleaf before, and he says he doesn't want a logo for the website... He likes the simplicity of the textual logo, and the name is close enough to "twitter" as it is, and using the twitter logo as well could be a shady legal area (according to him).

Soo... No logo, for now. But feel free to make one and post it here I guess.... Maybe he will change his mind 😉

**Comment by lionleaf** [comment]
Hi @reallinfo,

Amazing that you want to contribute! As you can tell we've had some
previous discussions around logos, and I've ended up with is a simplistic
version of the "default dweet" (go to dwitter.net and click the 'New dweet'
button to see it), which can be seen on our twitter page:
https://twitter.com/dwitter_net

I would be happy to get some suggestions and mock-ups from you, to see if
we can find a good concept.

I'm struggling coming up with good ideas for exactly what I concept would
be good, but I think the right way to go is simple geometric shapes
inspired by content on dwitter.net or old classic "demo"-effects (
https://en.wikipedia.org/wiki/Demoscene), like a twister (
https://www.dwitter.net/h/twister). Or inspired by the basic default dweet,
similar to what we already have, and I'll admit that I have a soft-spot for
the default dweet reference (see all the different versions people have
made here: https://www.dwitter.net/h/default/top )

Finally, I want to avoid a logo that uses twitter-imagery, or is based on
the 'dwitter' name.

Let me know if you are still interested, and I'd be excited to hear if you
have some ideas.

I'm available to chat about ideas and inspiration.

**Comment by reallinfo** [comment]
Hi @lionleaf i will deal with it at a convenient time. Can this matter issue open for a while?

**Comment by lionleaf** [comment]
No rush at all @reallinfo I'll just leave this open :)

**Comment by reallinfo** [comment]
Hi again, @lionleaf 

https://www.dwitter.net/h/default/top

I looked at the images here. I designed something like that. Logo idea is available below.

![dwt](https://user-images.githubusercontent.com/36298335/47563090-4e93dd80-d929-11e8-8140-f6e37314d7a5.jpg)

**Comment by dwitterer** [comment]
Hmm, nice idea, but I don't think that this kind of all-letters-in-one logo is very intuitive... I, for example, looked at it and initially though "what is that?" before I saw your little explanation, and it became clear as to what it was meant to be. It's just a bit confusing, that's all. And it's not really all that similar to the current logo either, to be honest :/ But we'll see what @lionleaf thinks of it. Some fan art stuff is cool to have anyway, as was said before... :D

(and keep in mind that favicons are tiny as hell, so any details just vanish)

**Comment by joeytwiddle** [comment]
Very clever! Although I'm worried I would cut myself on one of the sharp edges.

By the way, I see a doggie in there.

![doggie](https://user-images.githubusercontent.com/911799/47578035-ec63c880-d97a-11e8-87e0-a39642aa64ea.png)

**Comment by reallinfo** [comment]
hahaha a great imagination! @joeytwiddle :D

**Comment by kipkat** [comment]
l am a confirmed logo designer, if I have time, I can help you guys.

Vin, 26 oct. 2018, 19:13 reallinfo <notifications@github.com> a scris:

**Comment by pavelb** [comment]
Dwitter is creativity in 140 characters. Perhaps we can feature the number 140 and/or a famous dweet as the logo.

**Comment by dwitterer** [comment]
@pavelb This instantly popped into my head when I read that... A variation of sigveseb's famous 701 dweet, but with '140' on every square:

![screenshot from 2018-10-28 00-59-31](https://user-images.githubusercontent.com/36137355/47610447-7aa87f00-da4d-11e8-9662-4a22e1d8748d.png)

Two iterations only:

![screenshot from 2018-10-28 01-05-58](https://user-images.githubusercontent.com/36137355/47610454-a75c9680-da4d-11e8-81d7-07a1ac39b304.png)

(Ignore the slight misalignments, I did this kinda quickly and something went wrong dimensions-wise apparently... I could fix it if I wanted to I guess)

**Comment by kipkat** [comment]
I dont think that is enough minimalistic but it is representative. I
suggest a 140 made of the default 50x200 rects.

Dum, 28 oct. 2018, 03:07 dwitterer <notifications@github.com> a scris:

**Comment by lionleaf** [comment]
Hi @reallinfo and everyone else.

Again thanks a lot for your contribution, but after some consideration I still prefer the simplicity of the current logo. 

For now I'm making the executive decision to officially go for the current one (and it will be more prominent when #428 merges).

That being said; you're more than welcome to iterate on logo ideas, and if something great comes up I'm it is possible to change. But for now I will consider this solved and will spend my energy elsewhere :)

PS: While `140` in the logo would be better than the `dwitter` name; it's still something that theoretically could change at some time.

@reallinfo Unless you have something else you would like to add, feel free to close this
