### ISSUE TITLE
Suggestion: howto section

### ISSUE THREAD

**Issue by fractalf** [lionleaf/dwitter#454]
Would be cool to somhow add a howto section. It's really hard to get started making somethink cool.

Maybe each demo could have a "README.md" field or something, where the author can explain what's really going on for others to learn.

Also a global howto listing common techneques used to do basic up to advanced stuff.

A global example section listing very basic demos and how they are done.

Yes, I know what some might think, "just duck/google it", but info on js demo/codegolf is really scattered etc

Thanks for a great little fun app! :)

**Comment by lionleaf** [comment]
Yes! I think a getting started tutorial that's integrated with the site would be very useful. 

I believe this is the same as #23 , so closing this as a duplicate for now. Let me know if you believe it's not a duplicate.

As for other resources, may I recommend the  wiki page here for basic techniques: https://github.com/lionleaf/dwitter/wiki  

as well as the great dweet dissections blog series by [u/KilledByAPixel](https://www.dwitter.net/u/KilledByAPixel) for deep dives on more advanced dweets here: https://frankforce.com/?tag=dwitter

**Comment by fractalf** [comment]
@lionleaf Yea #23 is pretty much the same, except one feature. I'll post a comment there to keep it all in one place :) Might I suggest a quick win of adding a link to the dwitter wiki from the /about page or menu?
