### ISSUE TITLE
Suggestion: add the ability to list dweets by length

### ISSUE THREAD

**Issue by Lucas-C** [lionleaf/dwitter#455]
Hi,

Today I was looking what were the shortest dweets ever made...

I had a look at the API and there doesn't seem to be a way to sort dweets by code length.

I'm willing to submit a PR to add this feature, but I'd like to know what you would consider to be the best approach here:
- add an new route `/dweet/shortest` in `dwitter/dweet/urls.py` ?
- add a query param to allow filtering on `views.DweetViewSet` based on this recipe: https://stackoverflow.com/a/39885624/636849 ?
- add an endpoint to export all dweets as JSON, which woul allow anyone to perform the query they want on the data set without bloating the API ?

What do you think ?

**Comment by KilledByAPixel** [comment]
There is a way...

http://dweetabase.3d2k.com

Click the box sort length. It may take a few seconds to load because this contains every dweet (~12K)

**Comment by Lucas-C** [comment]
Awesome, thanks !
This one lokks like a winner: https://www.dwitter.net/d/14792
Feel free to close this if the feature suggested does not seem useful/necessary

**Comment by lionleaf** [comment]
Thanks! I'll close this for now then, but will keep it in mind if I update the API in the future
