### ISSUE TITLE
Initial character count is off

### ISSUE THREAD

**Issue by jrsmb** [lionleaf/dwitter#462]
### Description
The site now, since 2019-12-27, uses a new counting system that fixed counting errors with compressed dweets. Seems to work fine but this is another counting error I found.
A dweet shows up with a character count that is wrong. If you delete a character and type one again, the count is different than before. In the dweet that I found the count is 143 before and 139 after a quick edit. See attachments.

### Reproduction
I don't know for how long it will be possible:
Right now you can go to the home page https://www.dwitter.net, scroll down to load more and maybe the tenth dweet is by LimeLight. If you reached it by scrolling down, the bug should be visible. If you go to the individual dweet share page, it's not there. More dweets will have this problem but they are hard to find

### Comment by lionleaf
Pretty sure this is the counting line that disagrees with the javascript counting (and with the database, or else it couldn't have been posted): https://github.com/lionleaf/dwitter/blob/master/dwitter/templates/snippets/dweet_card.html#L95

---
![](https://i.imgur.com/iOpiaNS.png)

![](https://i.imgur.com/fdBcLWJ.gif)

**Comment by lionleaf** [comment]
Mentioned by @kipkat and @KilledByAPixel in discord, this might be cause by counting newline as two characters (\n\r). Will investigate.
