### ISSUE TITLE
Problem with newlines on Windows

### ISSUE THREAD

**Issue by PhiLhoSoft** [lionleaf/dwitter#51]
In a dweet like http://dweet.dwitter.net/id/246 I used newlines instead of `;` for readability purpose.

Problem 1: I am on Windows, hitting Return on a textarea apparently inserts a CRLF. So the site counts 2 characters instead of 1, which isn't economical... :-/
Somehow, there should be a replacement of CRLF by LF internally (and back, if needed).

Problem 2: HTML of `textarea` forces `row="3"`, so I can't resize the area (on Chrome, at least).

Problem 3: HTML relies on `maxlength="140"` to ensure the dweet is legal, but as said, it counts end of lines on Windows as two chars. If JS can't fix `s/CRLF/LF/`, perhaps the limit should be enforced by JS only? With special handling of CRLF sequence, of course.

Problem 4: character counter counts EOL as one char, so we can be stuck at **136/140** when we have 4 EOLs... Puzzling at first.

**Comment by lionleaf** [comment]
Solved by #56
