### ISSUE TITLE
1 Remixes?

### ISSUE THREAD

**Issue by Hope41** [lionleaf/dwitter#527]
When a dweet only has one remix it says '1 remixes' not '1 remix'.
It's only a small bug, but it keeps annoying me

**Comment by lionleaf** [comment]
Thanks for the report, I assume you're referring to the new beta.dwitter.net frontend? 

I fixed it here: https://github.com/dwitter-net/dwitter-frontend/pull/111

**Comment by Hope41** [comment]
Thanks, is there a way I can report primarily beta.dwitter.net frontend glitches without
posting it on this main page?

**Comment by joeytwiddle** [comment]
Just a tip for developers:

If you are finding it too much hassle to separate 1 from the other cases (perhaps you are writing in a language without `_ ? _ : _`)

then a rough solution is to instead use a noun with two interpretations. For example:

```
n + " remix(es)"
```

would appear as:

> 0 remix(es)
> 1 remix(es)
> 2 remix(es)

which is not beautiful, but at least it's never wrong!
