### ISSUE TITLE
First comment by author as a sticky comment on top

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#78]
When posting a dweet, allow a description that is posted as the first comment. This comment should then be "sticky" and emphasized.

**Comment by iver56** [comment]
Good idea, but be careful. Before a draft is restored, ask the user if he/she wants to apply it. The code in the draft may be heavy or bad code that was the reason why the user shut down the browser tab.

**Comment by lionleaf** [comment]
This was probably a response to #92
