### ISSUE TITLE
After posting a new dweet, see share-link

### ISSUE THREAD

**Issue by iver56** [lionleaf/dwitter#79]
When a user posts a new dweet he should receive some kind of positive message about the new dweet. F.ex. "Great! If you want to show off your new dweet, share the following link:"
`<shareable link>`

**Comment by lionleaf** [comment]
Suggestion: Redirect to the direct-link after posting with a message. Something like:

<img width="750" alt="screenshot 2016-10-19 20 07 14" src="https://cloud.githubusercontent.com/assets/610925/19533436/ab480ee8-9637-11e6-802d-dca5b5150069.png">
