### ISSUE TITLE
Comment field becomes red after submit

### ISSUE THREAD

**Issue by iver56** [lionleaf/dwitter#88]
After I submit a comment and the field is automatically cleared, validation kicks in and the field becomes red (browser: Firefox). This isn't a defect per se, but it's slightly distracting.

![bilde](https://cloud.githubusercontent.com/assets/1470603/21313499/7f4fbe22-c5f2-11e6-95ab-1a5e9f32ae01.png)

If one could reset the form into a "pristine" state after submit, that would probably fix the issue.

Or maybe the novalidate attribute could help? http://stackoverflow.com/a/31170547/2319697

**Comment by lionleaf** [comment]
Ah, which browser are you using? I might actually just remove 'required' on
the field as the other fix should make the submit just not work if it's not
valid

**Comment by iver56** [comment]
I use Firefox (edited original post)
